spawn:
  world: 'world'
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 90.0
  yaw: 0.0
  teleport-to-spawn-on-join: false

autobroadcast:
  delay: 60 #Delay between autobroadcasts in seconds
  announcements:
    - '%nl%&6&lTIP &r&7➥ &eThis is an example %nl%of multi %nl%line broadcast%nl%' #Add %nl% for a new line
    - '%nl%&6&lActinium &r&7➥ &eThank you for downloading &6Actinium%nl%'

discord:
  message: '&9&lDISCORD &8&l- &fJoin our discord by clicking here'
  link: 'https://discord.gg/example'

messages:
  firstjoin: '&7&o%player% has joined for the first time!'
  join: '&7&o%player% has joined!'
  quit: '&c&l- &7%player%' #This message is only sent to players with the actinium.staff permission